export const USER_SIGN_IN_REQUEST = "USER_SIGN_IN_REQUEST";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_IN_FAIL = "USER_SIGN_IN_FAIL";
export const GET_RESPONSE_TIME_REQUEST ='GET_RESPONSE_TIME_REQUEST' 
export const GET_RESPONSE_TIME_SUCCESS ='GET_RESPONSE_TIME_SUCCESS'
export const GET_RESPONSE_TIME_FAIL ='GET_RESPONSE_TIME_FAIL' 